// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var SERVICES = [
  {
    name: "Hydro Strategy",
    tagline: "Data-driven paid media & performance marketing",
    includes: [
      "Meta & Google Ads management",
      "Conversion tracking & attribution",
      "Landing page CRO",
      "Weekly performance reporting"
    ]
  },
  {
    name: "Blaze Creative",
    tagline: "High-converting creative production",
    includes: [
      "Ad creative (static & video)",
      "Brand identity systems",
      "Content production",
      "Creative testing frameworks"
    ]
  },
  {
    name: "Full Growth Partnership",
    tagline: "Strategy + creative as an embedded team",
    includes: [
      "Everything in Hydro Strategy",
      "Everything in Blaze Creative",
      "Dedicated growth lead",
      "Monthly strategy sessions"
    ]
  }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List HydroBlaze services",
  description: "Return the list of marketing services HydroBlaze offers with taglines and what each includes.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var TIERS = [
  {
    id: "starter",
    name: "Starter",
    priceMonthly: 1500,
    currency: "USD",
    bestFor: "Early-stage brands validating paid channels",
    includes: ["1 paid channel", "Basic creative refresh", "Bi-weekly reporting"]
  },
  {
    id: "growth",
    name: "Growth",
    priceMonthly: 3500,
    currency: "USD",
    bestFor: "Scaling brands ready to compound performance",
    includes: ["Up to 3 channels", "Full creative production", "Weekly reporting & strategy"]
  },
  {
    id: "premium",
    name: "Premium",
    priceMonthly: 7500,
    currency: "USD",
    bestFor: "Established brands needing an embedded growth team",
    includes: ["Unlimited channels", "Dedicated growth lead", "Custom analytics dashboards"]
  }
];
var get_pricing_default = defineTool2({
  name: "get_pricing",
  title: "Get HydroBlaze pricing",
  description: "Return HydroBlaze pricing tiers. Optionally filter to a single tier by id (starter, growth, premium).",
  inputSchema: {
    tier: z.enum(["starter", "growth", "premium"]).optional().describe("Optional tier id to return only that pricing tier.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ tier }) => {
    const result = tier ? TIERS.filter((t) => t.id === tier) : TIERS;
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { tiers: result }
    };
  }
});

// src/lib/mcp/tools/contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get HydroBlaze contact info",
  description: "Return the ways to get in touch with HydroBlaze, including the lead form URL and social links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      website: "https://hydroblaze.com",
      leadForm: "https://hydroblaze.com/#contact",
      bookingNote: "Prospective clients can submit the contact form on the website to book a discovery call."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xtdemrqoeraogjwwfses";
var mcp_default = defineMcp({
  name: "hydroblaze-mcp",
  title: "HydroBlaze MCP",
  version: "0.1.0",
  instructions: "Public information about HydroBlaze, a performance-marketing agency. Use `list_services` to see offerings, `get_pricing` for tier details, and `get_contact_info` for how prospects can reach the team.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, get_pricing_default, contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
